FROM python:3.13-slim

WORKDIR /app

COPY . .

RUN pip install --upgrade pip \
  && pip install uv \
  && uv pip install --system .

CMD ["streamlit", "run", "main.py", "--server.port=8501", "--server.address=0.0.0.0"]